"""
This script processes a list of requests exported by a web browser
in order to output the list of card_uris.
The requests were generated by attempting to post many poll tweets
through the browser, but blocking the status update requests from being
sent, only allowing the poll creation requests to pass through.
"""

import json

with open("requests.har", "r", encoding="utf-8") as file:
    r = json.load(file)

card_uris = []

for entry in r["log"]["entries"]:
    card_uris.append(json.loads(entry["response"]["content"]["text"])["card_uri"])

with open("card_uris.txt", "w") as file:
    file.write("\n".join(card_uris))
