"""
This script uses selenium/poll_tweeter.py to post twitter polls
with questions generated by question_generator.py.
"""

import json
from time import sleep
from urllib.parse import urlencode
from question_generator import generate
from selenium/poll_tweeter import tweet_poll

def post_question():
    status = generate()
    print("Posting question: '{}'... ".format(status), end="")
    tweet_poll(status)
    print("done! :3")

SECONDS_BETWEEN_TWEETS = 23 * 60 * 60 #every 23 hours

while False:
    post_question()
    sleep(SECONDS_BETWEEN_TWEETS)
